### ISSUE TITLE
does> ?

### ISSUE THREAD

**Issue by wboeke** [tdwsl/aster-forth#1]
Hi,
Are there any plans to implement the does> word? It would make this forth so much more interesting ...

**Comment by tdwsl** [comment]
Hi,

I haven't actually worked on this for a while, and it's quite unstable, with some lousy code (segfaults, etc). I'm surprised someone found it, and as for your question, I won't be adding does>, sorry. When I get the time, though, I might try writing an overhaul, and when I do I'll be sure to include does>.

Thanks for showing an interest!

**Comment by wboeke** [comment]
It's not only interest, but even impatience!
Your program already is rather robust. However, if you try:
1 2 !
then aster does nothing, while most other forth's simply crash. What should happen is a message: "address out of range". 
Aster already can do a lot, compared to other small forth's, and the C code is nicely written!

**Comment by tdwsl** [comment]
Hey, sorry for the late reply, but I've just uploaded the new version of Aster FORTH.

On your point about address bound checking, Aster actually starts addressing from 0, so 1 2 ! is valid - try "base .": it's zero! Anyway, your point is taken and the new version has bounds checking. Not everything is here, but it _does_ feature a (compile-only) version of does>. A key difference is that I decided to go for the integer datatype for the stack instead of void*, so I hope that won't cause any problems with any uses you had in mind. I might change that back actually.

Again, thanks for showing interest - it really gave me the motivation to continue with this project. I've heard there's a trope about people who write an interpreter to learn FORTH then call it a day, and whilst I've been interested in FORTH for a while, I definitely fit into that stereotype a little - I don't think I'd ever used does> before.

Don't hold back about making other suggestions either - I won't do a complete rewrite next time!

**Comment by wboeke** [comment]
It works! Thanks a lot.
About CREATE and DOES>: I saw an implementation (github: post4-master) of the words VALUE an DO that took about 50 lines of forth. Then an implementation using CREATE an DOES> (github: vfc-master) in 6 lines of forth.
For me, forth is like a complicated puzzle. This counts for the implementation (in C) as well as for examples in forth. There are a few usual testcases, like 8queens, Conway's game of life, a simple text editor, or example programs from Rosetta that you can try to implement. Forth is so refreshing different from other languages, and with a little fantasy you feel the spirit of its inventor, who did unbelievable things with the language: control an observatory, design chips etc.
