### ISSUE TITLE
80000000 ?

### ISSUE THREAD

**Issue by wboeke** [tdwsl/aster-forth#4]
In aster_boot.h there are lines like:
: 0< 80000000 and 0= 0= ;
containing a big, arbitrary number. If you make 2 extra words: '<' and '>', a much cleaner implementation is possible, like this:
": <= > 0 = ; : >= < 0 = ; : 0< 0 < ; : 0> 0 > ; : 0<= 0 <= ; : 0>= 0 >= ;\n"

Another big number: 24000. Why?
For the rest: happy with aster. It's my favourite forth now.
Maybe it's a good idea to compile sometimes with -Wall. There are some minor issues then.

**Comment by tdwsl** [comment]
Hi,
You're right about the big arbitrary number in comparisons. I've added 0>= and 0< in C to clean things up a bit.
As for 24000, that's the size of the buffer for all string literals, as currently they aren't placed inline with the rest of the code in a word. I guess I might get around to changing this at some point. Also, I've tried compiling with -Wall, and I think I've fixed all the warnings now.
It's great to hear that it's your favourite, although I'm sure there are better forths out there! And thanks for all the troubleshooting, it definitely wouldn't be the same otherwise.
